"""add task isCompleted column

Revision ID: 046e0de8a5d1
Revises: 74eb277d7578
Create Date: 2023-10-09 14:55:26.910532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046e0de8a5d1'
down_revision = '74eb277d7578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isCompleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('isCompleted')

    # ### end Alembic commands ###
